version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
     -  ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  notejam:
    image: sursin2701/notejam:latest
    # build: ./notejam
    container_name: notejam-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./notejam/.env
    ports:
      - "3000:3000"
    networks:
      - my_network
   
    
    
  
volumes:
  pgdata:

networks:
  my_network:
