apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam-backend
  namespace: default

spec:
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  #   type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: notejam-backend
  template:
    metadata:
      labels:
        app: notejam-backend
    spec:
      
      containers:
        - image: sursin2701/note-jam:v1.0.2
          name: notejam
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_URL


            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: secret
                    key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: POSTGRES_DB

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name:   configmap
                  key: POSTGRES_PORT

            - name: PORT
              valueFrom:
                  configMapKeyRef:
                    name: configmap
                    key: PORT



          volumeMounts:
            - name: notejam-storage
              mountPath: /app/storage
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: notejam-storage
          persistentVolumeClaim:
            claimName: notejam-pvc
