# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
#   volumeMode: Filesystem
  

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  # namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi