apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data: 
  POSTGRES_USER: cG9zdGdyZXM=      
  POSTGRES_PASSWORD: c3VyYWo= 
  POSTGRES_DB: Tm90ZXRha2Vy  
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnN1cmFqQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9Ob3RldGFrZXI=